# Setup
title:               HackSlashRun
url:                 oceanclub1970.github.io
baseurl:             '/hackslashrunblog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Paul Moloney

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
